basic:
    name: 'https://pintlerpt.com/'
    environments:
        production: 'https://pintlerpt.com/'
        staging: 'https://k8vtrexlh2.wpdns.site/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /pay-my-bill
        - /about
        - /services
        - /our-services/manual-therapy
        - /our-services/sports-medicine
        - /our-services/spinal-manipulation
        - /our-services/orthopedic-rehabilitation
        - /our-services/vestibular-rehabilitation
        - /our-services/post-concussion-rehabilitation
        - /our-services/headache-rehabilitation
        - /our-services/pelvic-health-therapy
        - /new-patients
        - /frequently-asked-questions
        - /contact
        - /terms-of-service
        - /privacy-policy
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
